### ISSUE TITLE
当点数用完之后，就会出错.(when the credits are used up, there is a problem)

### ISSUE THREAD

**Issue by Sen-Ran** [vra/bing_brush#1]
当点数用完之后，我发现返回的response里面没有response.headers["Location"]这一项了，导致报错。具体问题出现在bing_brush.py,line83:  redirect_url = response.headers["Location"].replace("&nfy=1", "").

我感觉问题在于,当使用点数的时候,在点击创建image之后,会出现进度条,此时并没有切断session连接.而当点数用完之后,不会出现进度条,此时也许session连接已经被切断了,所有response里面并没有location这一项.

**Comment by vra** [comment]
感谢反馈，我修改一下代码，返回提示信息而不是报错

**Comment by Sen-Ran** [comment]
> 感谢反馈，我修改一下代码，返回提示信息而不是报错

很感谢您的这个项目, 这个问题可以修复吗?
因为即使点数用完了,在网页里image creator也是可以继续生成的,只是所花费的时间更多.
我尝试了修复,但是发现:(1)有点数余额的时候,session.post()得到的返回response中有重定向到生成图片的 response.headers["Location"].(2)当点数用尽的时候,即使session.post()发送相同的请求,response中也没有重定向的response.headers["Location"],但是会有一个待生成图片的id: response.headers["X-Ceto-ref"],但是这个id是无效的,服务器并没有真正生成这张图片.(3)当点数用尽时,在网页端生成是可以正常重定向的.
尝试修复了一下午,还是没有成功,希望以上信息对您有帮助.

**Comment by vra** [comment]
Hi @HumphreyB613 ,
您好，感谢您花时间使用和调试这个工具，您的调试信息对最终解决问题很有帮助，我照着您的思路，发现没有返回Location是因为post请求中有一个参数rt，默认用的是4，如果boosts用完后,rt=4的post请求就不返回Location，因此需要改成rt=3（走慢速通道）再发送请求，然后就可以生成了，虽然时间确实会增加。

基于这个解决方案，我提交了[更新代码](https://github.com/vra/bing_brush/commit/a8629cf734132ff1d5285cc212e0e4a7c62fd37c)，也在pypi上发布了0.1.2版本，欢迎您继续使用，如果有任何问题可以继续讨论:)

**Comment by Sen-Ran** [comment]
> Hi @HumphreyB613 , 您好，感谢您花时间使用和调试这个工具，您的调试信息对最终解决问题很有帮助，我照着您的思路，发现没有返回Location是因为post请求中有一个参数rt，默认用的是4，如果boosts用完后,rt=4的post请求就不返回Location，因此需要改成rt=3（走慢速通道）再发送请求，然后就可以生成了，虽然时间确实会增加。
> 
> 基于这个解决方案，我提交了[更新代码](https://github.com/vra/bing_brush/commit/a8629cf734132ff1d5285cc212e0e4a7c62fd37c)，也在pypi上发布了0.1.2版本，欢迎您继续使用，如果有任何问题可以继续讨论:)

您好,非常感谢您的付出! 这是很棒的项目!
